//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashelFirmwareAutomatedTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CashelFirmwareAutomatedTest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string EXCELDATA_BUSBAR_FEEDER_CHANNELNUMBER {
            get {
                return ResourceManager.GetString("EXCELDATA_BUSBAR_FEEDER_CHANNELNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel_Number_DSP1.
        /// </summary>
        internal static string EXCELDATA_Channel_Number_DSP1 {
            get {
                return ResourceManager.GetString("EXCELDATA_Channel_Number_DSP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel_Number_DSP2.
        /// </summary>
        internal static string EXCELDATA_Channel_Number_DSP2 {
            get {
                return ResourceManager.GetString("EXCELDATA_Channel_Number_DSP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string EXCELDATA_DSP_FEEDER_NUMBER {
            get {
                return ResourceManager.GetString("EXCELDATA_DSP_FEEDER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP_FR_Cabling.
        /// </summary>
        internal static string EXCELDATA_FRCABLING {
            get {
                return ResourceManager.GetString("EXCELDATA_FRCABLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMP_PQ_Cabling.
        /// </summary>
        internal static string EXCELDATA_PQCABLING {
            get {
                return ResourceManager.GetString("EXCELDATA_PQCABLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusbarFeederMap.
        /// </summary>
        internal static string EXCELDATA_SHEETNAME_BUSBAR_FEEDER_MAP {
            get {
                return ResourceManager.GetString("EXCELDATA_SHEETNAME_BUSBAR_FEEDER_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabling.
        /// </summary>
        internal static string EXCELDATA_SHEETNAME_CABLING {
            get {
                return ResourceManager.GetString("EXCELDATA_SHEETNAME_CABLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSPFeederMap.
        /// </summary>
        internal static string EXCELDATA_SHEETNAME_DSP_FEEDER_MAP {
            get {
                return ResourceManager.GetString("EXCELDATA_SHEETNAME_DSP_FEEDER_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSPChannelMap.
        /// </summary>
        internal static string EXCELDATA_SHEETNAME_DSPCHANNEL {
            get {
                return ResourceManager.GetString("EXCELDATA_SHEETNAME_DSPCHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pmp:pmp/data/busbar_feeder_map/busbar[{0}]/channel_count&quot;.
        /// </summary>
        internal static string LOCATOR_NAME_BUSBAR_CHANNELCOUNT {
            get {
                return ResourceManager.GetString("LOCATOR_NAME_BUSBAR_CHANNELCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pmp:pmp/data/busbar_feeder_map/busbar[{0}]/channel[{1}]&quot;.
        /// </summary>
        internal static string LOCATOR_NAME_BUSBAR_MAP_BUSBAR_CHANNEL {
            get {
                return ResourceManager.GetString("LOCATOR_NAME_BUSBAR_MAP_BUSBAR_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pmp:pmp/data/busbar_feeder_map/feeder[{0}]/channel[{1}]&quot;.
        /// </summary>
        internal static string LOCATOR_NAME_BUSBAR_MAP_FEEDER_CHANNEL {
            get {
                return ResourceManager.GetString("LOCATOR_NAME_BUSBAR_MAP_FEEDER_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pmp:pmp/data/busbar_feeder_map/feeder[{0}]/associated_busbar&quot;.
        /// </summary>
        internal static string LOCATOR_NAME_FEEDER_ASSOCIATED_BUSBAR {
            get {
                return ResourceManager.GetString("LOCATOR_NAME_FEEDER_ASSOCIATED_BUSBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;pmp:pmp/data/busbar_feeder_map/feeder[{0}]/channel_count&quot;.
        /// </summary>
        internal static string LOCATOR_NAME_FEEDER_CHANNELCOUNT {
            get {
                return ResourceManager.GetString("LOCATOR_NAME_FEEDER_CHANNELCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;//a[text()=&apos;busbar[{0}]&apos;]&quot;.
        /// </summary>
        internal static string LOCATOR_XPATH_BUSBAR {
            get {
                return ResourceManager.GetString("LOCATOR_XPATH_BUSBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dsp1_feeder_map&apos;]/following-sibling::div/table[{0}]/tbody/tr/td[2]/a.
        /// </summary>
        internal static string LOCATOR_XPATH_DSP1_FEEDERMAP_DSP_FEEDER {
            get {
                return ResourceManager.GetString("LOCATOR_XPATH_DSP1_FEEDERMAP_DSP_FEEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[text()=&apos;dsp2_feeder_map&apos;]/following-sibling::div/table[{0}]/tbody/tr/td[2]/a.
        /// </summary>
        internal static string LOCATOR_XPATH_DSP2_FEEDERMAP_DSP_FEEDER {
            get {
                return ResourceManager.GetString("LOCATOR_XPATH_DSP2_FEEDERMAP_DSP_FEEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;//a[text()=&apos;feeder[{0}]&apos;]&quot;.
        /// </summary>
        internal static string LOCATOR_XPATH_FEEDER {
            get {
                return ResourceManager.GetString("LOCATOR_XPATH_FEEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/div/table[5]/tbody/tr/td[3]/span/a/select&quot;.
        /// </summary>
        internal static string XPATH_BUSBAR {
            get {
                return ResourceManager.GetString("XPATH_BUSBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/a&quot;.
        /// </summary>
        internal static string XPATH_CHANNELNUMBER {
            get {
                return ResourceManager.GetString("XPATH_CHANNELNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[5]/tbody/tr/td[2]/div/table[{0}]/tbody/tr/td[3]/span/a/input&quot;.
        /// </summary>
        internal static string XPATH_dsp1_channels_map_dsp_channel {
            get {
                return ResourceManager.GetString("XPATH_dsp1_channels_map_dsp_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[6]/tbody/tr/td[2]/div/table[{0}]/tbody/tr/td[3]/span/a/input&quot;.
        /// </summary>
        internal static string XPATH_dsp2_channels_map_dsp_channel {
            get {
                return ResourceManager.GetString("XPATH_dsp2_channels_map_dsp_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/div/table[4]/tbody/tr/td[3]/span/a/select&quot;.
        /// </summary>
        internal static string XPATH_FEEDER {
            get {
                return ResourceManager.GetString("XPATH_FEEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/div/table[6]/tbody/tr/td[3]/span/a/select&quot;.
        /// </summary>
        internal static string XPATH_PHASE {
            get {
                return ResourceManager.GetString("XPATH_PHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[1]/tbody/tr/td[2]/div/table[1]/tbody/tr/td[2]/div/table[{0}]/tbody/tr/td[3]/span/a/input.
        /// </summary>
        internal static string XPATH_pqp_calcno_config {
            get {
                return ResourceManager.GetString("XPATH_pqp_calcno_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/div/table[2]/tbody/tr/td[3]/span/a/select&quot;.
        /// </summary>
        internal static string XPATH_SI_UNIT {
            get {
                return ResourceManager.GetString("XPATH_SI_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;/html/body/form/table/tbody/tr/td/table[2]/tbody/tr/td/div/table[{0}]/tbody/tr/td[2]/div/table[9]/tbody/tr/td[3]/span/a/select&quot;.
        /// </summary>
        internal static string XPATH_USAGE {
            get {
                return ResourceManager.GetString("XPATH_USAGE", resourceCulture);
            }
        }
    }
}
